services:
  # Servicio Frontend (Vue 3 / Vite + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: catalogo_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=/api

  # Servicio Backend / API Express
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: catalogo_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/catalogobulk
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=clave_secreta_bulkers_2026
      - JWT_EXPIRES_IN=2h
    depends_on:
      - mongo
      - redis

  # Base de Datos MongoDB 7
  mongo:
    image: mongo:7
    container_name: catalogo_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: catalogobulk
    volumes:
      - mongo_data:/data/db

  # Servicio de Caché y Cola (Redis 7)
  redis:
    image: redis:7-alpine
    container_name: catalogo_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
